// Generated by CoffeeScript 1.9.2
var oceanUtil, showErrorNoticeWindow, showInfoNoticeWindow, showSuccessNoticeWindow, showWarningNoticeWindow;

showInfoNoticeWindow = function(noticeMessage, timeout) {
  if (timeout == null) {
    timeout = 5000;
  }
  return $.UIkit.notify({
    message: noticeMessage,
    status: 'info',
    timeout: timeout,
    pos: 'top-center'
  });
};

showWarningNoticeWindow = function(noticeMessage) {
  return $.UIkit.notify({
    message: noticeMessage,
    status: 'warning',
    timeout: 5000,
    pos: 'top-center'
  });
};

showErrorNoticeWindow = function(noticeMessage) {
  return $.UIkit.notify({
    message: noticeMessage,
    status: 'danger',
    timeout: 5000,
    pos: 'top-center'
  });
};

showSuccessNoticeWindow = function(noticeMessage) {
  return $.UIkit.notify({
    message: noticeMessage,
    status: 'success',
    timeout: 5000,
    pos: 'top-center'
  });
};

oceanUtil = {
  showInfoNoticeWindow: showInfoNoticeWindow,
  showWarningNoticeWindow: showWarningNoticeWindow,
  showErrorNoticeWindow: showErrorNoticeWindow,
  showSuccessNoticeWindow: showSuccessNoticeWindow
};

module.exports = oceanUtil;
