// Generated by CoffeeScript 1.9.2
var BlogsVue, HeaderVue, SiteDesVue, config;

config = require('../config');

HeaderVue = require('./../vue/header_vue');

SiteDesVue = require('./../vue/site_des_vue');

BlogsVue = require('./../vue/blogs_vue');

module.exports = function() {
  new HeaderVue({
    el: config.domIds.mainHeader
  });
  if (window.oceanContext.userInfo.login) {
    return new BlogsVue({
      el: config.domIds.mainContent
    });
  } else {
    return new SiteDesVue({
      el: config.domIds.mainContent
    });
  }
};
