// Generated by CoffeeScript 1.9.2
var HeaderVue, LoginVue, config;

config = require('../config');

HeaderVue = require('./../vue/header_vue');

LoginVue = require('./../vue/login_vue');

module.exports = function() {
  console.log('Login page');
  new HeaderVue({
    el: config.domIds.mainHeader
  });
  return new LoginVue({
    el: config.domIds.mainContent
  });
};
