// Generated by CoffeeScript 1.9.2
var HeaderVue, RegisterVue, config;

config = require('../config');

HeaderVue = require('./../vue/header_vue');

RegisterVue = require('./../vue/register_vue');

module.exports = function() {
  console.log('Register page');
  new HeaderVue({
    el: config.domIds.mainHeader
  });
  return new RegisterVue({
    el: config.domIds.mainContent,
    data: {}
  });
};
