// Generated by CoffeeScript 1.9.2
var HeaderVue, config;

config = require('../config');

HeaderVue = require('./../vue/header_vue');

module.exports = function() {
  console.log('Register page');
  return new HeaderVue({
    el: config.domIds.mainHeader
  });
};
