// Generated by CoffeeScript 1.9.2
var MyUtil, SiteDesVue, Vue, config, exchangeService;

Vue = require('vue');

exchangeService = require('./../service/exchange_service');

MyUtil = require('./../util/myutils');

config = require('./../config');

SiteDesVue = Vue.extend({
  template: require('../template/site_des.html'),
  beforeCompile: function() {}
});

module.exports = SiteDesVue;
