// Generated by CoffeeScript 1.9.2
var $, RegisterFilter, config, director, pageService, routes;

director = require('director');

$ = window.$;

config = require('./config');

RegisterFilter = require('./vue_filter/register_filter');

pageService = require('./service/page_service');

routes = require('./routes');

$(document).ready(function() {
  var router;
  $.ajaxPrefilter(function(options, originalOptions, jqXHR) {
    return options.crossDomain = {
      crossDomain: true
    };
  });
  RegisterFilter.registerFilter();
  router = director.Router(routes);
  return pageService.checkAndRefreshLocalStorage(function() {
    return router.init('/index');
  });
});
