// Generated by CoffeeScript 1.9.2
var index, login, oauth, register, routes;

index = require('./route/index');

oauth = require('./route/oauth');

login = require('./route/login');

register = require('./route/register');

routes = {
  '/index': function() {
    return index();
  },
  '/login': function() {
    return login();
  },
  '/register': function() {
    return register();
  },
  '/oauth': function() {
    return oauth();
  }
};

module.exports = routes;
